---
# tasks file for logrotate

- name: Asegurar que logrotate esté instalado
  ansible.builtin.apt:
    name: logrotate
    state: present
    update_cache: yes

- name: Asegurar que el directorio /etc/logrotate.d exista
  ansible.builtin.file:
    path: /etc/logrotate.d
    state: directory
    mode: '0755'

- name: Realizar copia de seguridad de logrotate.conf
  ansible.builtin.copy:
    src: /etc/logrotate.conf
    dest: /etc/logrotate.conf.bak
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
    backup: yes  # opcional: conserva backup anterior si ya existe .bak

- name: Copiar el archivo logrotate.conf desde template
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Forzar ejecución de logrotate con nueva configuración
  ansible.builtin.command: logrotate -f /etc/logrotate.conf
  become: yes
